name: Build

on:
  push:
    tags-ignore:
      - "v*"
  pull_request:

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo check
        run: cargo check
      - name: cargo build --release
        run: cargo build --release
